### ISSUE TITLE
scvsmag in v4

### ISSUE THREAD

**Issue by gempa-jabe** [SED-EEW/SED-EEW-SeisComP-contributions#2]
In order to compile this along with SC 4.x you should remove scvsmag from branch v4. Otherwise the target `scvsmag` is defined twice.

**Comment by FMassin** [comment]
But this is fixed by https://github.com/swiss-seismological-service/sed-SeisComP-contributions/pull/4 
?????

**Comment by FMassin** [comment]
I mean of course there must be conflicts (vsmag, dmvs, ...) with previous versions of sed-contrib, but that is why I did PR #4 in sed-SeisComP-contributions. You want me to do that somewhere else? Or what else can I do?

**Comment by FMassin** [comment]
I thought it was all already defined and agreed... Yes I would be happy if a maintainer of  sed-SeisComP-contributions could do it.

**Comment by FMassin** [comment]
Ho I see, I need to call my v4 branch v5? And keep v4 compatible with...sed-SeisComP-contributions v4?

**Comment by luca-s** [comment]
It is just a matter of how new SeisComP releases are created and the SED repositories need to adhere to that way of operating. At the moment when there is a new major release (e.g. 4.x or the next 5.x) a corresponding branch (e.g. branch v4 or v5) is created in every SC repositories (common, main, seedkink, etc) and contribution repositories (SED, IPGP, etc). When a minor versions is created (e.g. 4.1, 4.1.2 etc) a new tag is created in the corresponding branch (e.g. v4). The changes that happened in the master branch are not applied! That happens at the next release (e.g. v5). If you want to backport a change scheduled for the next release (v5) in a previous version (v4.x.y) you need to cherry pick the commits you want from the master branch to the specific version brach (e.g. v4).  

That is what Jan meant. We need to cherry pick the changes from the master to branch v4 if we want that changes in the next v4 version. If we don't care, we can wait for the next major release to have that changes applied.

**Comment by gempa-jabe** [comment]
Please hold on a second. The contributions repository is fine. Everything for v4 is included (scvsmag and friends). In its master branch all the VS apps are removed, also fine. I am not talking about that repository. I am explicitly talking about this repository. I you want to build sed-eew for v4 then you must exclude scvsmag, because it is already part of the v4 branch of contrib-sed. And scvsmag must only be removed for the v4 branch. Alternatively you can rename it to have both versions, one for VS and one for EEW. I don't know if they differ in functionality.

**Comment by gempa-jabe** [comment]
Regarding Luca's remark about v4 is also correct. Of course you can check the API version in your cmake scripts and enable / disable certain applications and also account for API changes. Then we can build the master branch against any SeisComP version. For now we have the v4 branch which we use to build the package for 4.x.y.

**Comment by luca-s** [comment]
@gempa-jabe I like your approach of having a release branch in the repository. I don't believe we want to switch to master branch only. Anyway, sorry for introducing noise in the discussion, I now understand your point.

**Comment by FMassin** [comment]
The v4 branch in this repo was not made with this in mind sorry. I should redo a proper v4 branch without conflicting modules.

But from a functional point of view, since scvsmag and co. stay in sed-contrib until seiscomp v5 there isn't any purpose for compiling the Eew repo with seiscomp v4 : scfinder does not compile without FinDer, sceewenv, sccewlog are just the new versions of scenvelope and scvsmaglog... 

So please only include master in v5 or nightly compilations @gempa-jabe ?

**Comment by gempa-jabe** [comment]
Yes, the master branch will only be included in 5.x. As you have requested to also build eew for 4.x we did that and that has caused the conflict I am reporting. If you don't want us to build eew for 4.x, let us know and this issue is resolved without further actions.

**Comment by FMassin** [comment]
Yes please only build it with v5. 

Jan, thank you so much for your patience, as I'm still figuring all of this out.

And thanks to you both Jan and Luca for opening the first issue (I take that term in the very generic way) on this repo! 

Please don't stop trying to make me understand things. And please also feel free to put ideas and and kind of feedback in the discussion area...
