### ISSUE TITLE
The SED SeisComP contributions data model extension

### ISSUE THREAD

**Issue by mrdimentio** [SED-EEW/SED-EEW-SeisComP-contributions#31]
I can't find how to install "The SED SeisComP contributions data model extension" could someone help me how to do it? I find it a big obstacle for the installation

**Comment by FMassin** [comment]
Hello

Thanks for your interest. Please use the link given in the readme or install the precompiled binaries via gsm (https://www.gempa.de/news/2021/07/gsm/ ) or seiscomp.de. Issues are related to code development. Please ask open such questions in the discussion panel of the repo. I must close this topic.
