### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gempa-jabe** [SED-EEW/SED-EEW-SeisComP-contributions#32]
https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/blob/3c7941f785ead7b7f3148b93cbdce9060ae99e5a/apps/eew/scvsmag/timeline.cpp#L140C34-L140C34

```
2023-07-20 21:05:44 INFO seiscomp/src/extras/sed-eew/apps/eew/scvsmag/timeline.cpp: In member function ‘bool Seiscomp::Timeline::feed(const Seiscomp::DataModel::VS::Envelope*)’:
seiscomp/src/extras/sed-eew/apps/eew/scvsmag/timeline.cpp:140:25: error: ‘gainUnit’ was not declared in this scope
  140 |                         gainUnit = stream->gainUnit();
      |                         ^~~~~~~~
```

Add a type to gainUnit for correct declarations, at least `auto`. Please test compilation prior to committing your changes otherwise the builds on our end will fail.

**Comment by FMassin** [comment]
Yes I know sorry I am fixing it.

**Comment by FMassin** [comment]
The code compilation is now fixed and I hope the code is correct. @gempa-jabe would you mind telling me what you think about my little changes in timeline.cpp here https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/commit/f21964598ff27e75fee565f136304aa609da5f30 ?
