### ISSUE TITLE
Problem with sorting coordinates

### ISSUE THREAD

**Issue by sceylan** [SED-EEW/SED-EEW-SeisComP-contributions#37]
Shouldn't the ```sort``` command below be used with the ```-g``` or ```-n``` option for numerical sorting? 

https://github.com/SED-EEW/SED-EEW-SeisComP-contributions/blob/47001e3909a002de0aa12e713ef20d5bebf97512/apps/eew/scfinder/utils/makeFinderMask.sh#L39-L42

**Comment by FMassin** [comment]
-n is better?

**Comment by sceylan** [comment]
Yes, I think ```-n``` is better. According to the GNU manual, ```-g``` should be used if there is no alternative.

**Comment by FMassin** [comment]
Done. I hope it changes nothing in the results.
