### ISSUE TITLE
scvsmag must be removed from v4 branch

### ISSUE THREAD

**Issue by gempa-jabe** [SED-EEW/SED-EEW-SeisComP-contributions#4]
Please remove scvsmag from the v4 branch otherwise we cannot build the package for SeisComP 4.x.

**Comment by gempa-jabe** [comment]
Ok, I thought that as branch v4 was available that it should also work with v4. Fine, then we only build for v5. Thanks.

**Comment by FMassin** [comment]
May I just remove `scvsmag` from `apps/eew/CMakeLists.txt` ?

**Comment by gempa-jabe** [comment]
Actually all conflicting modules. scvsmag is one of them, yes.

**Comment by gempa-jabe** [comment]
It won't show up there. As it is not built with the distribution, it won't be part of the documentation. The documentation should be part of the addon package.

**Comment by FMassin** [comment]
@luca-s I thought scrtdd and eew would appear in the same way in https://docs.gempa.de/seiscomp/current/base/addons ?

**Comment by gempa-jabe** [comment]
Ah, you are talking about the external documentation. Yes, we will add that. The build recipes are not yet finished. Then we will also add the link to the SC documentation.

I was under the assumption that you requested the documentation to be included in the SC documentation.

**Comment by FMassin** [comment]
Absolutely not! And I am very happy with the current status.
